services:
  - type: web
    name: aolangfarm
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: dpg-d1lnh115pdvs73c6g44g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: aolangfarm
      - key: DB_USERNAME
        value: aolangfarm_user
      - key: DB_PASSWORD
        value: A9sICwudbDbTH6JIrMlkTorstOrXG0sJ
